a={
    "car": "toyota",
    "model": "camry",
    "images": "hgttps://soma images"
}

b= {
    "car": "toyota",
    "model": "camry",
    "images": ["hgttps://soma images"],
    "price" : "25000000",
    "is_published" : True
}


a= {"name": "Askar",  "list_name": "Erlanov",}
for k,v in a.items():
    print ("key:",k)
    print ("Value", v)

list_1 = [
    
    {
    "name": "Kanat",
    "list_name": "Erlanov",
    "age": 28
    },
    {"name": "Nurik",
    "list_name": "Nurillla",
    "age": 20
    },
    {"name": "Tuma",
    "list_name": "Terminal",
    "age": 21
    },  

      
]

for len   in a.items():
 print("frgvuy")